# client/netlify.toml
[build]
  # bu qovluqda olduğumuza görə artıq 'cd client' yazmağa ehtiyac yoxdur
  command   = "npm install && npm run build"
  # React (Vite) build nəticəsi dist/ qovluğunda yaranır
  publish   = "dist"
