# netlify.toml (repo kökündə, yəni front-un olduğu qovluqda)

[build]
  # npm install və build bu qovluqda (root) işləsin:
  command = "npm install && npm run build"
  # Vite build nəticəsi dist/ içində yaranır, onu yayımlayaq:
  publish = "dist"

# React Router varsa, bütün URL-ləri index.html-ə yönləndir:
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
